module.exports = {
    HBVOLURL: [
        'www.huobi.ge',
        'www.huobi.pe',
        'www.huobi.fm',
        'www.huobi.me',
        'www.huobi.ec',
        'www.huobi.com.vn',
        'www.huobi.com.gi',
        'www.huobi.uk.com',
        'www.huobi.com.bi',
        'www.huobi.ws',
        'www.huobi.mn',
        'www.huobi.ec',
        'www.huobi.li',
        'www.huobi.ci',
        'www.huobi.gf',
        'www.huobi.as',
        'www.huobi.pr',
        'www.huobi.sc',
        'www.huobi.be',
        'www.huobi.it',
        'www.huobi.cz',
        'www.huobi.sh',
    ],
    HBOTCURL: [
        'otc-api-hk.eiijo.cn',
        'otc-api.eiijo.cn',
    ]
};